//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Gallery
    {
        public long Id { get; set; }
        public string Url { get; set; }
        public Nullable<long> ProductId { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
