//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specification
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public long CategoryId { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
